### ISSUE TITLE
Buttons need "link" indication

### ISSUE THREAD

**Issue by dawnbarton** [SSAgov/uef-vscode-extension#16]
UEF snippet for button is difficult to use without knowing how to make it work. Please add help text or directions.

Example:

`<uef-button primary="false" target="#" name="insert-id">[Button]</uef-button>`

**Comment by CraigCecilSSA** [comment]
Yes, I need to make that easier (and quicker) to insert stuff like this for building out app flows quickly.

**Comment by CraigCecilSSA** [comment]
Resolved in #21 and #22
