### ISSUE TITLE
Please create/add some way to create header login/user number

### ISSUE THREAD

**Issue by dawnbarton** [SSAgov/uef-vscode-extension#17]
Please add an easy way to create a User name and supporting ID to indicate a logged-in state for users within mySSA or an application. Here is an example of something that might work:

[First Name, Last Name]
[ID Number (ssn/rep ID/emp number)]

Thanks!

**Comment by dawnbarton** [comment]
This could be the whole header, even - a way to add a mySSA header, pub website header, adjust header title for pub template app or pro temp app.

**Comment by CraigCecilSSA** [comment]
All good suggestions that I can add.

**Comment by CraigCecilSSA** [comment]
Resolved in #19 and #20
